"""
Fine-tune YOLO-World v2 on a custom dataset (few-shot friendly).

Dataset structure:
  dataset/
  ├── images/          # .jpg files
  ├── labels/          # .txt files (YOLO format, normalized)
  └── data.yaml        # auto-generated by this script, or provide manually

Each label .txt line:  <class_id> <x_center> <y_center> <width> <height>
All values normalized to [0, 1].

Usage:
  # Auto-generate data.yaml from class names:
  python scripts/finetune_yolo_world.py \
      --weights yolov8s-worldv2.pt \
      --data_dir dataset/cups_bottles/ \
      --classes "cup,bottle" \
      --epochs 30 \
      --out_dir weights/yolo_world_finetuned/

  # Or provide an existing data.yaml:
  python scripts/finetune_yolo_world.py \
      --weights yolov8s-worldv2.pt \
      --data dataset/cups_bottles/data.yaml \
      --epochs 30
"""

import argparse, os, sys
from pathlib import Path


def auto_split(data_dir):
    """Split images into train/val if not already split. Returns data.yaml path."""
    img_dir = Path(data_dir) / 'images'
    lbl_dir = Path(data_dir) / 'labels'

    if not img_dir.exists():
        raise FileNotFoundError(f"images/ not found in {data_dir}")
    if not lbl_dir.exists():
        raise FileNotFoundError(f"labels/ not found in {data_dir}. Annotate images first.")

    images = sorted([f.name for f in img_dir.glob('*.jpg')] + [f.name for f in img_dir.glob('*.png')])
    if not images:
        raise FileNotFoundError(f"No .jpg/.png files found in {img_dir}")

    # Check if already split
    train_img = img_dir / 'train'
    if train_img.exists():
        return  # already split

    # Create split: 85% train, 15% val
    n_train = max(1, int(len(images) * 0.85))

    for split, subset in [('train', images[:n_train]), ('val', images[n_train:])]:
        os.makedirs(img_dir / split, exist_ok=True)
        os.makedirs(lbl_dir / split, exist_ok=True)
        for fname in subset:
            os.rename(img_dir / fname, img_dir / split / fname)
            stem = Path(fname).stem
            lbl = lbl_dir / f'{stem}.txt'
            if lbl.exists():
                os.rename(lbl, lbl_dir / split / f'{stem}.txt')

    print(f"Auto-split: {n_train} train / {len(images) - n_train} val")


def write_data_yaml(data_dir, classes):
    """Generate data.yaml for the dataset."""
    yaml_path = Path(data_dir) / 'data.yaml'
    if yaml_path.exists():
        print(f"Using existing {yaml_path}")
        return

    abs_path = Path(data_dir).resolve()
    with open(yaml_path, 'w') as f:
        f.write(f"path: {abs_path}\n")
        f.write(f"train: images/train\n")
        f.write(f"val: images/val\n")
        f.write(f"nc: {len(classes)}\n")
        f.write("names:\n")
        for i, name in enumerate(classes):
            f.write(f"  {i}: {name}\n")
    print(f"Generated {yaml_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--weights', type=str, default='yolov8s-worldv2.pt',
                        help='Base YOLO-World weights')
    parser.add_argument('--data_dir', type=str, default=None,
                        help='Dataset directory (with images/ and labels/)')
    parser.add_argument('--data', type=str, default=None,
                        help='Path to data.yaml (alternative to --data_dir)')
    parser.add_argument('--classes', type=str, default=None,
                        help='Comma-separated class names, e.g. "cup,bottle"')
    parser.add_argument('--epochs', type=int, default=30)
    parser.add_argument('--imgsz', type=int, default=640)
    parser.add_argument('--batch', type=int, default=4)
    parser.add_argument('--lr0', type=float, default=0.001)
    parser.add_argument('--out_dir', type=str, default='weights/yolo_world_finetuned/')
    args = parser.parse_args()

    # Resolve data config
    if args.data:
        data_yaml = args.data
        if args.classes:
            classes = [c.strip() for c in args.classes.split(',') if c.strip()]
        else:
            raise ValueError("--classes required when using --data (for set_classes)")
    elif args.data_dir:
        if not args.classes:
            raise ValueError("--classes required when using --data_dir. E.g. --classes 'cup,bottle'")
        classes = [c.strip() for c in args.classes.split(',') if c.strip()]
        auto_split(args.data_dir)
        write_data_yaml(args.data_dir, classes)
        data_yaml = str(Path(args.data_dir) / 'data.yaml')
    else:
        raise ValueError("Either --data_dir or --data required")

    print(f"Classes: {classes}")
    print(f"Data config: {data_yaml}")
    print(f"Output dir: {args.out_dir}")
    print(f"Training: epochs={args.epochs}  imgsz={args.imgsz}  batch={args.batch}  lr0={args.lr0}")

    # Import here to avoid slow startup when just checking args
    from ultralytics import YOLOWorld

    model = YOLOWorld(args.weights)
    model.set_classes(classes)

    results = model.train(
        data=data_yaml,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        lr0=args.lr0,
        device=0,
        project=args.out_dir,
        name='train',
        exist_ok=True,
        amp=True,
        cos_lr=True,
        warmup_epochs=2,
        weight_decay=0.0005,
        momentum=0.937,
        augment=True,
        # Few-shot specific: freeze early layers
        freeze=10,
    )

    # Copy best model to out_dir
    # Ultralytics saves under runs/detect/{project}/{name}/weights/best.pt
    best_pt = Path('runs') / 'detect' / args.out_dir / 'train' / 'weights' / 'best.pt'
    os.makedirs(Path(args.out_dir), exist_ok=True)
    out_pt = Path(args.out_dir) / 'model_best.pt'
    if best_pt.exists():
        import shutil
        shutil.copy(best_pt, out_pt)
        print(f"\nFine-tuned model saved to: {out_pt}")
        print(f"\nRun it with:")
        print(f"  --detector_type yolo_world \\")
        print(f"  --yolo_weights {out_pt} \\")
        print(f"  --text_prompt '{'a ' + '. a '.join(classes)}.'")


if __name__ == '__main__':
    main()
